#!/usr/bin/env sh

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
echo "lol"
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child # floating windows always stay on top
yabai -m config window_topmost               on
# enable borders
yabai -m config window_border                on
# no clue what this is
yabai -m config insert_feedback_color        0xff7abf45
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15 #40
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15 #15

# SIP Required
# prevent border from being under the active window
yabai -m config active_window_border_topmost on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_border_width          5 
yabai -m config active_window_border_color   0x001f6091
yabai -m config normal_window_border_color   0x00757575 #replace the 0x00 to 0xff if you want the borders
